[package]
name = "rand-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
rand = "0.8.5"
reqwest = {version="0.12.9", features=["blocking", "json"]}
serde = {version="1.0.214", features=["derive"]}
serde_json = "1.0.132"
